services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn fast_api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev